Feature/counter
leeji0805/react_tutorial pull request #5
Opened 2024-03-29 07:09 UTC by leeji0805

카운터 및 토탈을 재업합니다

2024-03-29 07:18 UTC, leeji0805 commented
카운터를 스태시로 넣은 후 커밋하고 다른 기능을 만들면서 제출한걸로 착각했습니다...ㅠ

2024-04-02 06:56 UTC, blackpigsoft commented
draft 상태로 되어 있어서 리뷰가능한 상태로 변경하였습니다.
혹시 제가 잘못한거면 커멘트 달아주시기 바랍니다.

2024-04-02 07:00 UTC, blackpigsoft requested changes
깔끔하게 작업 잘 해주신것 같아요
작업 감사합니다.

케이스몇개만 추가해주시고 다시 리뷰요청해주시면 approve  하겠습니다.

2024-04-02 07:00 UTC, blackpigsoft commented on src/utils/cal.test.js
> +  ];
추가적인 케이스가 의미있게 추가되었으면 합니다.
예를 들면 이 함수를 사용하는 사람이 케이스를 보면서
이 함수는 음수는 대응이 되는 것인가 궁금할 수도 있다고 하면
음수가 들어간 사례를 보여주는 것도 좋을 방법입니다.

2024-04-02 07:01 UTC, blackpigsoft commented
아 제가 잘못 보았는데
review branch 를 만들어서 review branch 에 pr 다시 요청해주시기 바랍니다.

2024-04-08 12:24 UTC, merged